name: Check the frontend

on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:
  workflow_dispatch:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "node_version=$(cat .github/nodejs.version)" >> $GITHUB_ENV
      - name: "use node ${{ env.node_version }}"
        uses: actions/setup-node@v3
        with:
          node-version: "${{ env.node_version }}"

      - name: Install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate
  
      - name: Install dependencies with pnpm
        working-directory: frontend
        run: pnpm install --frozen-lockfile

      - name: Lint check
        working-directory: frontend
        run: pnpm run lint
      - name: Format check
        working-directory: frontend
        run: pnpm run prettier
      - name: Unit & Integration tests
        working-directory: frontend
        run: pnpm run test
      - name: Smoke & Acceptance tests
        working-directory: frontend
        run: |
          pnpm run build-storybook --quiet
          pnpm playwright install
          pnpm dlx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "pnpm dlx http-server storybook-static --port 6006 --silent" \
            "pnpm dlx wait-on tcp:127.0.0.1:6006 && pnpm run test-storybook"
