name: Deploy stack [dev]

on:
  workflow_dispatch:

env:
  CLOUDFRONT_FRONTEND_DISTRIBUTION_ID: # to be set during the bulid
  ECR_REPO_FRONTEND_NAME: # to be set on initial infra provision
  TERRAFORM_ROOT: ./terraform/dev
  NODE_VERSION: 18
  ENV: dev
  REDIS_URL: ${{ vars.REDIS_URL }}

  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_docker_image_tag: ${{ github.sha }}
  TF_LOG: ERROR

  # UNCOMMENT FOR DATABASE (1 of 5)
  # TF_VAR_db_password: this_should_be_loaded_from_secrets_12345

jobs:
  # only provision the ECR initially so we have somewhere to push the image to
  ecr_frontend:
    name: Provision ECR for frontend
    runs-on: ubuntu-22.04
    environment: dev
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: ${{env.TERRAFORM_ROOT}}

      - name: Terraform Validate
        id: validate
        run: terraform validate
        working-directory: ${{env.TERRAFORM_ROOT}}

      - name: Terraform Plan
        id: plan
        working-directory: ${{env.TERRAFORM_ROOT}}
        run: |
          terraform plan \
          -target=module.app_infra.aws_ecr_repository.frontend_ecr_repo \
          -out ./app_frontend_erc.out
  
      - name: Create ECR repo
        id: apply
        run: terraform apply -auto-approve ./app_frontend_erc.out
        working-directory: ${{env.TERRAFORM_ROOT}}

  frontend_build:
    name: Build Next.js app
    needs: ecr_frontend
    runs-on: ubuntu-22.04
    environment: dev
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.8
          terraform_wrapper: false

      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: ${{env.TERRAFORM_ROOT}}

      - name: Output terraform variables to file
        id: output
        working-directory: ${{env.TERRAFORM_ROOT}}
        run: |
          terraform output -json > ../../terraform-frontend-outputs.json

      # use terraform outputs to set workflow variables from terraform outputs
      - name: Set variables from Terraform Outputs
        run: |
          outputs=$(cat terraform-frontend-outputs.json)

          ecr_frontend_repo_name=$(echo $outputs | jq -r .frontend_ecr_repo_name.value)
          echo "ECR_REPO_FRONTEND_NAME=$ecr_frontend_repo_name" >> $GITHUB_ENV

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ env.ECR_REPO_FRONTEND_NAME }}
          IMAGE_TAG: ${{ env.TF_VAR_docker_image_tag }}
        run: |
          cd frontend && docker build \
          --build-arg ENV=${{ env.ENV }} \
          --build-arg REDIS_URL=${{ env.REDIS_URL }} \
          -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

  deploy:
    name: Deploy infra & app
    needs: [frontend_build]
    runs-on: ubuntu-22.04
    environment: dev
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: ${{env.TERRAFORM_ROOT}}

      - name: Terraform Validate
        id: validate
        run: terraform validate
        working-directory: ${{env.TERRAFORM_ROOT}}

      - name: Terraform Plan
        id: plan
        working-directory: ${{env.TERRAFORM_ROOT}}
        run: |
          terraform plan \
          -out ./app.out

      - name: Terraform Apply
        id: apply
        run: terraform apply ./app.out
        working-directory: ${{env.TERRAFORM_ROOT}}

      - name: Output terraform variables
        id: output
        working-directory: ${{env.TERRAFORM_ROOT}}
        run: |
          echo "### Hello world! :rocket:" >> $GITHUB_STEP_SUMMARY
          terraform output

      - name: Output terraform variables to file
        id: output-to-file
        working-directory: ${{env.TERRAFORM_ROOT}}
        run: |
          terraform output -json > ../../terraform-outputs.json

      - name: Set variables from Terraform Outputs for CloudFront
        run: |
          outputs=$(cat terraform-outputs.json)

          cloudfront_frontend_distribution_id=$(echo $outputs | jq -r .cloudfront_frontend_distribution_id.value)
          echo "CLOUDFRONT_FRONTEND_DISTRIBUTION_ID=$cloudfront_frontend_distribution_id" >> $GITHUB_ENV
  
      - name: Cloudfront Invalidation
        uses: chetan/invalidate-cloudfront-action@master
        env:
          DISTRIBUTION: ${{ env.CLOUDFRONT_FRONTEND_DISTRIBUTION_ID }}
          PATHS: '/'
          AWS_REGION: 'eu-west-2'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}