name: Playwright Tests
on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request: null
  workflow_dispatch: null
jobs:
  tests:
    name: "Perform e2e tests"
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "node_version=$(cat .github/nodejs.version)" >> $GITHUB_ENV
      - name: "use node ${{ env.node_version }}"
        uses: actions/setup-node@v3
        with:
          node-version: "${{ env.node_version }}"

      - name: Install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate
    
      - name: Install dependencies with pnpm
        working-directory: frontend
        run: pnpm install --frozen-lockfile

      - name: Install Playwright Browsers
        working-directory: frontend
        run: pnpm playwright install --with-deps

      - name: Run Playwright tests
        working-directory: frontend
        run: pnpm playwright test

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: frontend/playwright-report/
          retention-days: 30
